# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '26a65500-b05f-4a4c-a7dd-73a9e7a59dcb'
  imageRepository: 'malevarrokart'
  containerRegistryn: 'myacr21942.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

steps:
- script: |
    export TRIVY_AUTH_URL=$(URL)
    export TRIVY_USERNAME=$(USERNAME)
    export TRIVY_PASSWORD=$(PASSWORD)
    echo "[+] Fetching Trivy"
    export TRIVYVERSION=$(git ls-remote --refs --sort="version:refname" --tags https://github.com/aquasecurity/trivy | cut -d/ -f3-|tail -n1 | sed -e 's/^.//')
    echo "[+] Trivy Version:" ${TRIVYVERSION}
    wget -nv --no-cache https://github.com/aquasecurity/trivy/releases/download/v${TRIVYVERSION}/trivy_${TRIVYVERSION}_Linux-64bit.deb
    echo "[+] Installing Trivy"
    sudo dpkg -i trivy_${TRIVYVERSION}_Linux-64bit.deb
    echo "[+] Trivy Installed "${TRIVYVERSION}
    echo "[+] Running Trivy"
    echo "***Vulneability Assesment***"
    echo "[+] Writing Trivy Text File" 
    trivy image -f table --exit-code 0 $(containerRegistryn)/$(imageRepository) > ./trivy_results.txt
    echo "***SBOM Analysis***"
    echo "[+] Writing Trivy SBOM JSON File" 
    trivy image --scanners vuln --format cyclonedx --output ./trivy_sbom_results.json --exit-code 0 $(containerRegistryn)/$(imageRepository)
    echo "***Docker Compliance Analysis***"
    echo "[+] Writing Trivy Docker Compliance File" 
    trivy image --compliance docker-cis $(containerRegistryn)/$(imageRepository) > ./trivy_compliance_results.txt
